# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.9.0"

default_platform :ios

platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Default CI lane"
  lane :ci do
    test
    coverage
  end

  desc "Runs all the tests"
  lane :test do
    pod_lib_lint
    scan(
      device: "iPhone XS"
    )
    # slack(
    #   default_payloads: [:git_author],
    #   message: "Successfully tested: "+git_branch+", commit: "+sh("git log --pretty=format:'%h' -n 1")+" :rocket:"
    # )
  end

  desc "Slather sends code coverage to Coveralls"
  lane :coverage do
    slather(
      proj: "GTForceTouchGestureRecognizer.xcodeproj",
      scheme: "GTForceTouchGestureRecognizer-iOS",
      coveralls: true
    )
  end

  desc "Clean environment after all operations"
  lane :clean do
    clean_build_artifacts
  end

  after_all do |lane|
    clean_build_artifacts
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

end
