# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.9.0"

default_platform :ios

platform :ios do

  before_all do
  end

  desc "Default CI lane"
  lane :ci do
    test
    coverage
  end

  desc "Runs all the tests"
  lane :test do
    pod_lib_lint
    scan(
      device: "iPhone XS"
    )
  end

  desc "Slather sends code coverage to Coveralls"
  lane :coverage do
    slather(
      travis: true,
      proj: "GTForceTouchGestureRecognizer.xcodeproj",
      scheme: "GTForceTouchGestureRecognizer-iOS",
      source_directory: "Sources",
      coveralls: true
    )
  end

  desc "Clean environment after all operations"
  lane :clean do
    clean_build_artifacts
  end

  after_all do |lane|
    clean
  end

  error do |lane, exception|
  end

end
